### ISSUE TITLE
More problems with opEquals

### ISSUE THREAD

**Issue by atilaneves** [pbackus/sumtype#16]
This code fails with an assertion failure:

```d
import sumtype;

void main() {
    assert(
        Node(
            Struct(
                "Outer",
                [
                    Node(Struct("Inner", [ Node(Field(Type(Int()), "x")) ])),
                    Node(Field(Type(UserDefinedType("Inner")), "inner")),
                ],
            )
        )

     ==

        Node(
            Struct(
                "Outer",
                [
                    Node(Struct("Inner", [ Node(Field(Type(Int()), "x")) ])),
                    Node(Field(Type(UserDefinedType("Inner")), "inner")),
                ],
            )
        )
    );
}


alias Node = SumType!(
    Struct,
    Field,
);


struct Struct {
    string spelling;
    Node[] nodes;
}


struct Field {
    Type type;
    string spelling;
}


alias Type = SumType!(
    Int,
    UserDefinedType,
);


struct Int {}

struct UserDefinedType {
    string spelling;
}

```

**Comment by pbackus** [comment]
Reduced test-case:

```d
import sumtype;

void main() {
    // this succeeds
    assert(Node([Node("x")]) == Node([Node("x")]));
    // this fails
    assert(Node([Node([Node("x")])]) == Node([Node([Node("x")])]));
}


alias Node = SumType!(
    This[],
    string,
);
```

This is really weird.

**Comment by pbackus** [comment]
Took a look in gdb. The problem is that the `__equals` function in `object.d` isn't calling `SumType`'s `opEquals` overload. Specifically, [this `static if` condition](https://github.com/dlang/druntime/blob/v2.083.0/src/object.d#L398) is evaluating to false when it should be true.

**Comment by pbackus** [comment]
Confirmed this is the same bug in both the original and reduced versions.

**Comment by pbackus** [comment]
Figured it out. As I suspected, this is a compiler bug. Here's what's happening, explained in terms of the reduced version I posted in an earlier comment:

1. [The `static if` condition that guards the definition of `Node.opEquals`](https://github.com/pbackus/sumtype/blob/b42a3cc90c321e60354f58f7257a3cfb130cd83a/src/sumtype.d#L295) invokes `isEqualityComparable` on the `const`-qualified version of each of the types in `Node.Types`. One of those types is `const(Node[])`.
2. `isEqualityComparable!(const(Node[]))` reduces to, essentially, `__traits(compiles, { if (const(Node[]).init == const(Node[]).init) {} })`.
3. The equality comparison in the if statement above is lowered to `object.__equals(const(Node[]).init, const(Node[]).init)`.
4. This lowering causes the compiler to generate the template instance `object.__equals!(const(Node), const(Node))`. (The template arguments to `__equals` are the element types of the arrays.)
5.  To do so, the compiler performs semantic analysis on the body of `object.__equals`. During that analysis [this `static if` condition](https://github.com/dlang/druntime/blob/v2.083.0/src/object.d#L398) is evaluated. Since we're still deciding whether or not to define `Node.opEquals` (see step 1), the condition evaluates to false.
6. The template instance `object.__equals!(const(Node), const(Node))` is cached to avoid redundant semantic analysis passes.
7. Later, in the body of `opEquals`, the template labmda containing the expression `value == rhsValue` is instantiated for the `const`-qualified version of each of the types in `Node.Types`, including `const(Node[])`.
8. In the instance for `const(Node[])`, the equality expression is lowered to `object.__equals(value, rhsValue)`.
9. The cached template instance `object.__equals!(const(Node), const(Node))` is re-used for this call and fails to call `Node.opEquals`, because it was generated before `Node.opEquals` existed.

Essentially, it's a cache invalidation problem in the compiler. The `__equals` instance *should* be discarded once the `__traits(compiles)` expression that created it has been fully evaluated, but it isn't, so it does the wrong thing when it's later instantiated "for real."

This also explains why removing `staticMap!(ConstOf, ....)` fixes the bug: without `ConstOf`, the `__traits(compiles)` expression instantiates `__equals!(Node, Node)`, but the body of `opEquals` still calls `__equals!(const(Node), const(Node))`. Since the template arguments are different, there's no collision.
