### ISSUE TITLE
Nested sumtypes and `alias this`

### ISSUE THREAD

**Issue by SirNickolas** [pbackus/sumtype#27]
Found a bug while trying to represent an AST with `SumType`s. Here’s a reduced example:

```d
alias A = SumType!int;

struct B {
    A a;
    int y;

    alias a this;
}

alias C = SumType!B;

pragma(msg, C.Types); // (SumType!int), i.e. (A), though expected (B).

// This test fails:
@safe unittest {
    auto c = C(B(A(1), 123));
    c.match!((B b) {
        b.a.match!((int x) => assert(x == 1));
        assert(b.y == 123);
    });
    static assert(!__traits(compiles, C(A(1))));

    // This one is questionable.
    // I guess it might introduce some gotchas, so I'd forbid it as well.
    static assert(!__traits(compiles, c.match!(
        (A a) => a.match!((int x) => assert(x == 1)),
    )));
}
```

**Comment by pbackus** [comment]
This is a bug in the way `ReplaceType`, and by extension `ReplaceTypeUnless`, handles types that `alias this` a member whose type is a template. Reduced example:

```d
import std.typecons: ReplaceType;
struct A(T) {}
struct B { A!int a; alias a this; }
static assert(is(ReplaceType!(void, void, B) == B));
// Error: static assert:  `is(A!int == B)` is false
```

The relevant code in `ReplaceType` is:

```d
else static if (is(T[0] : U!V, alias U, V...))
{
    // handle template case
}
else static if (is(T[0] == struct))
    // handle struct case
```

Because the first condition uses `:` rather than `==` in its `is` expression, it treats `B`, which implicitly converts to `SumType!int` via `alias this`, as though it were identical to `SumType!int`.

**Comment by pbackus** [comment]
Turns out this is a known bug ([dlang issue 19703](https://issues.dlang.org/show_bug.cgi?id=19703)) with an open Phobos PR (dlang/phobos#6880).
