### ISSUE TITLE
trying to isolate a DMD bug when sumtype is involved

### ISSUE THREAD

**Issue by dewf** [pbackus/sumtype#35]
First of all, this is pretty clearly a DMD issue so feel free to close this without mercy. I'm merely asking here because I am a metaprogramming novice and don't know enough to properly reduce sumtype with dustmite, without losing the subtlety of the bug - ie, it guts the whole file to the point of triggering the error every time, whereas the essence of the bug is that seemingly irrelevant changes, like the location of a class declaration, affect whether SumType is copyable or not.

example: https://gist.github.com/dewf/a27a45b8632866c2cf10d557a18abf4b

I have played a bit with protecting sections from dustmite removal (via DustMiteNoRemoveStart/Stop), but to no avail. For example I got it to the point where commenting a module-level "import std" made the difference between the error or not - but I have no idea if that's normal for D metaprogramming. (Seems odd that a 'static if' would just silently evaluate to false if a symbol were missing, though...)

Anyhow, just wondering if you have any insight on reducing / isolating the part of sumtype involved, without losing the essence of the DMD bug. No expectations - I presume you're a busy man with limited time to look into these sorts of things.

cheers and thanks for writing sumtype in the first place!

**Comment by pbackus** [comment]
Further reduced:

```d
struct SumType(T) {
    import std.traits: isCopyable;
    static if (!isCopyable!T)
        @disable this(this);
}

struct CallbackType1 {
    bool[Class1] func;   // changing to Class1[] compiles OK
}

// moving Class1 above CallbackType1 compiles OK
class Class1 {
    SumType!CallbackType1 _callback;
    this(SumType!CallbackType1 callback) { // commenting out this ctor compiles OK
        _callback = callback;
    }
}
```

**Comment by pbackus** [comment]
Here's my best attempt at an explanation:

1. During semantic analysis of `CallbackType1`, the forward reference to `Class1` triggers on-demand semantic analysis of `Class1`, which in turn triggers on-demand semantic analysis of `SumType!CallbackType1`.

2. Normally, this would trigger on-demand analysis of `CallbackType1`, but the compiler notices it's already started analyzing `CallbackType1` and terminates the recursion.

3. While analyzing `SumType!CallbackType1`, the compiler evaluates `isCopyable!CallbackType1`. The source code for `isCopyable` looks like this:

    ```d
    enum isCopyable(S) = is(typeof(
        { S foo = S.init; S copy = foo; }
    ));
    ```

    When the lambda inside `isCopyable` attempts to declare an instance of `CallbackType1` as a local variable, it fails, because semantic analysis of `CallbackType1` is still in progress and its size is not yet known. You can verify this by copy & pasting the lambda above into the reduced version of `SumType`, before the `static if` statement. Doing so will produce the following error:

    ```
    Error: struct `onlineapp.CallbackType1` no size because of forward reference
    ```

    Because of this error, compilation of the lambda fails, and `isCopyable!CallbackType1` evaluates to `false`.

4. Swapping the order of the declarations fixes the issue because it changes DMD's semantic-analysis "call stack" from this:

    > CallbackType1 → Class1 → SumType!CallbackType1

    to this:

    > Class1 → SumType!CallbackType1 → CallbackType1

    As long as `SumType!CallbackType1` is encountered before `CallbackType1`, DMD is able to finish analyzing `CallbackType1` before it evaluates `isCopyable!CallbackType1`, and thus does not encounter the error described above.

Fixing this in DMD is likely to be quite difficult. However, it *may* be possible to find a workaround for `isCopyable` that allows it to work with incomplete types.

**Comment by dewf** [comment]
Wow, you truly went above and beyond! Thank you so much, for the reduction and cogent analysis. I have a lot to learn about D (and its limits), but the wisdom and helpfulness of D veterans is invaluable.

I will credit/link to your explanation here when I make the bug report for this.

Thanks again!

**Comment by skoppe** [comment]
I was running into a similar issue:

```D
/+dub.sdl:
dependency "sumtype" version="~>0.9.3"
+/
import sumtype;

struct A {}
struct B { AorB[] as; } // removing the [] shows the underlying cause: forward declaration
alias AorB = SumType!(A, B);

void main() {
    AorB a;
    AorB c = a; // Error: struct `sumtype.SumType!(A, B).SumType` is not copyable because it is annotated with `@disable`
}
```

The way I "solved" it was by making AorB a struct:

```D
struct AorB {
    SumType!(A,B) ab;
}
```

**Comment by pbackus** [comment]
It must be that `AorB[]` triggers semantic analysis of `AorB` if it's an alias, but not if it's struct. Which I guess makes sense, since DMD knows without further examination that `struct AorB` is something it can create a pointer to, whereas `alias AorB` could refer to almost anything.

As expected, moving the alias declaration above the struct declarations also fixes the problem, since it changes the dependency chain from "B → SumType!(A, B)" to "SumType!(A, B) → B".

**Comment by skoppe** [comment]
> As expected, moving the alias declaration above the struct declarations also fixes the problem, since it changes the dependency chain from "B → SumType!(A, B)" to "SumType!(A, B) → B".

Yes you are correct. I somehow didn't manage to do that in my code, will try again.

Apparently the `[]` plays a part as well, since removing them (even with your ordering suggestion) makes dmd complain about a forward declaration error.

It is a wonder this indirect self referencing works at all.

**Comment by pbackus** [comment]
> Apparently the `[]` plays a part as well, since removing them (even with your ordering suggestion) makes dmd complain about a forward declaration error.

Removing the `[]` means that you have a struct which directly contains an instance of itself (B contains SumType!(A, B), which contains B), which is always an error, regardless of what order you declare things in.

**Comment by skoppe** [comment]
Ahh yes of course, otherwise the computer will implode. You'll need pointers in that case.
