### ISSUE TITLE
Confusing error message when matching immutable or const SumType

### ISSUE THREAD

**Issue by iK4tsu** [pbackus/sumtype#63]
```d
immutable SumType!int st;
st.match!(
	(ref int _) => true
);
```

```
Error: static assert:  "`handlers[0]` of type `bool function(ref int _) pure nothrow @nogc @safe` never matches"

instantiated from here: `matchImpl!(immutable(SumType!int))`
```

Trying to match a `ref` of an `immutable` or `const` SumType outputs this error, which makes total sense, however, it took me some time trying to find the issue. I don't know if it's easy to change the error message based on the implementation, but I think it could help others when facing the same problem.

Something like `cannot match 'ref' of immutable SumType, perhaps you mean 'const ref'?` would be a better straightforward message.

**Comment by pbackus** [comment]
I agree that the error message is confusing. Unfortunately, I don't think this can be fixed.

The problem here is that `match` uses `__traits(compiles)`, and *in general* there is no way to tell why a `__traits(compiles)` check failed. Even if I add code in to check for this specific case, there will always be similar cases that I can't detect; for example:

```d
st.match!(
    (ref value) { static assert(typeof(value) == int); return true; }
);
```

If you want to know why a handler failed to match, here's a method I've found to be effective:

1. Recompile the module with `-verrors=spec` and redirect the output to a file:

        dmd -verrors=spec -c source/mymodule.d >verrors.txt 2>&1

    If you're using `dub`, you can pass `-verrors=spec` using the `DFLAGS` environment variable.
        
2. Use `grep` to find errors that occurred in the offending source file:

        grep 'source/mymodule.d' verrors.txt
        
Somewhere in the output you will probably find the error you are looking for. If you need more information, you can use `grep -C` to show more context for each match or `grep -n` to get the line number so you can investigate manually.

**Comment by cpiker** [comment]
> I agree that the error message is confusing. Unfortunately, I don't think this can be fixed.
> 
> The problem here is that `match` uses `__traits(compiles)`
...

>    If you're using `dub`, you can pass `-verrors=spec` using the `DFLAGS` environment variable.

Thanks for providing a debugging recipe.  This was tripping me up as well.
